## Web settings
baseurl: ""
url: ""

## SEO
twitter_username: osd_it
github_username:  opensensensorsdata
title: osd
email: contact@osd.tools
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
image:
  twitter: /_assets/img/seo/psd-ogp-facebook.png
  facebook: /_assets/img/seo/osd-ogp-facebook.png
author: opensensensorsdata


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
