## Web settings
baseurl: ""
url: ""

## SEO
twitter_username: osd_it
github_username:  opensensensorsdata
title: osd
email: contact@osd.tools
description: > # this means to ignore newlines until "baseurl:"
  We deliver strategies and run projects of data reuse, making open data a valuable asset and a sustainable element of business models
image:
  twitter: /img/seo/psd-ogp-facebook.png
  facebook: /img/seo/osd-ogp-facebook.png
author: opensensensorsdata


# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
