## Web settings
baseurl: ""
url: ""

## SEO
twitter_username: osd_it
github_username:  opensensensorsdata
title: opensensorsdata
email: contact@osd.tools
description: > # this means to ignore newlines until "baseurl:"
  We deliver strategies and run projects of data reuse, making open data a valuable asset and a sustainable element of business models
author: opensensensorsdata

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/seo/osd-opg-facebook.png

# Favicon
touch_icon: assets/img/logos/apple-touch-icon-144-precomposed.png
favicon: assets/img/logos/favicon.ico


# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-assets
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

# Repository
# repository: opensensorsdata/opensensorsdata.github.io
