# Main Text
name: opensensorsdata
aka: osd
title: 'osd - manifattura open data'
subtitle: 'manifattura open data'
payoff: 'servizi e progetti di riuso dati'
description: Consegnamo strategie e gestiamo progetti di riuso dati, rendendo i dati aperti un bene prezioso e un elemento sostenibile per i modelli di business.

# Url
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Contact
twitter: osd_it
github:  opensensorsdata
facebook: opensensorsdata
email: contact@osd.tools

# SEO
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/seo/osd-opg-facebook.png

# Favicon
touch_icon: assets/img/logos/apple-touch-icon-144-precomposed.png
favicon: assets/img/logos/favicon.ico

# Build settings
markdown: kramdown
highlighter: rouge

#

sass:
  sass_dir: _sass
  style: compression


gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

# Collection
collections:
  documents:
    output: true
